baseURL = "https://sacredspace.netlify.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Sacred Space Yoga"
enableRobotsTXT = true

[[menu.desktop]]
    identifier = "Classes"
    name = "Classes"
    url = "/classes/"
    weight = 1
[[menu.desktop]]
    identifier = "Training"
    name = "Training"
    url = "/teacher-training/"
    weight = 2
[[menu.desktop]]
    identifier = "Sacred Service"
    name = "Sacred Service"
    url = "/sacred-service/"
    weight = 3
[[menu.desktop]]
    identifier = "doTerra"
    name = "doTerra"
    url = "/"
    weight = 4
[[menu.desktop]]
    identifier = "Blog"
    name = "Blog"
    url = "/"
    weight = 5
[[menu.desktop]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 6
[[menu.desktop]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 7
[[menu.mobile]]
    identifier = "Classes"
    name = "Classes"
    url = "/classes/"
    weight = 1
[[menu.mobile]]
    identifier = "Training"
    name = "Training"
    url = "/teacher-training/"
    weight = 2
[[menu.mobile]]
    identifier = "Sacred Service"
    name = "Sacred Service"
    url = "/sacred-service/"
    weight = 3
[[menu.mobile]]
    identifier = "doTerra"
    name = "doTerra"
    url = "/"
    weight = 4
[[menu.mobile]]
    identifier = "Blog"
    name = "Blog"
    url = "/"
    weight = 5
[[menu.mobile]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 6
[[menu.mobile]]
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    weight = 7
[[menu.footer]]
    identifier = "Classes"
    name = "Classes"
    weight = 2
    [[menu.footer]]
        identifier = "Schedule"
        name = "Schedule"
        url = "/schedule/"
        parent = "Classes"
        weight = 1
    [[menu.footer]]
        identifier = "Pricing"
        name = "Pricing"
        url = "/pricing/"
        parent = "Classes"
        weight = 2
    [[menu.footer]]
        identifier = "Private Classes"
        name = "Private Classes"
        url = "/"
        parent = "Classes"
        weight = 3
    [[menu.footer]]
        identifier = "Dig Deep"
        name = "Dig Deep"
        url = "/dig-deep/"
        parent = "Classes"
        weight = 4
[[menu.footer]]
    identifier = "Training"
    name = "Training"
    weight = 2
    [[menu.footer]]
        identifier = "Teacher Training"
        name = "Teacher Training"
        url = "/teacher-training/"
        parent = "Training"
        weight = 1
[[menu.footer]]
    identifier = "Sacred Service"
    name = "Sacred Service"
    weight = 3
    [[menu.footer]]
        identifier = "SS Classes"
        name = "SS Classes"
        url = "/"
        parent = "Sacred Service"
        weight = 1
    [[menu.footer]]
        identifier = "Community"
        name = "Community"
        url = "/sacred-service/"
        parent = "Sacred Service"
        weight = 2
[[menu.footer]]
    identifier = "doTerra"
    name = "doTerra"
    url = "/"
    weight = 4
[[menu.footer]]
    identifier = "Blog"
    name = "Blog"
    url = "/"
    weight = 5
[[menu.footer]]
    identifier = "About"
    name = "About"
    weight = 6
    [[menu.footer]]
        identifier = "Meet the Family"
        name = "Meet the Family"
        url = "/about/"
        parent = "About"
        weight = 1
    [[menu.footer]]
        identifier = "Ettiquette"
        name = "Ettiquette"
        url = "/ettiquette/"
        parent = "About"
        weight = 2
    [[menu.footer]]
        identifier = "FAQs"
        name = "FAQs"
        url = "/faqs/"
        parent = "About"
        weight = 3
[params.tracking]
    cloudinary_url = "https://res.cloudinary.com/pioneer-design/image/upload"
[params.publishing_settings]
    site_in_production = false

[mediaTypes]
  [mediaTypes."text/noExt"]
    suffixes = ""

[sitemap]
    filename = "sitepages.xml"

[outputFormats]
    [outputFormats.sitemapindex]
        baseName = "sitemapindex"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.sitepages]
        baseName = "sitepages"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.siteposts]
        baseName = "siteposts"
        isPlainText = false
        mediaType = "application/xml"
        path = "/"
    [outputFormats.redirects]
        baseName = "_redirects"
        isPlainText = true
        mediaType = "text/noExt"
        path = "/"
    [outputFormats.Algolia]
        baseName = "algolia"
        isPlainText = true
        mediaType = "application/json"
        notAlternative = true

[outputs]
  home = ["HTML", "sitemapindex", "sitepages", "siteposts", "RSS", "redirects", "Algolia"]

[params.algolia]
    appId = ""
    search_key = ""
    index_name = ""

[params.extra_tools]
    algolia_search = true
    font_awesome = true
    floating_header = true

[markup.goldmark.renderer]
unsafe= true